SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';

-- schema owner
CREATE ROLE sa WITH password '12033021';

-- create schema
CREATE SCHEMA order_migration AUTHORIZATION sa;

GRANT ALL PRIVILEGES ON DATABASE order_migration TO sa;

ALTER ROLE sa WITH LOGIN;

--  orders
CREATE DATABASE orders;

-- Использование базы данных orders
\c orders;

-- create schema
CREATE SCHEMA orders AUTHORIZATION sa;

create table orders.order_request
(
    msg_id                                   varchar(128) not null
        constraint foiv__order_request_pk
            primary key,
    sys_id                                   varchar(30),
    tar_id                                   varchar(30),
    acc_number                               varchar(20),
    external_doc_id                          varchar(128),
    task_id                                  varchar(128) not null,
    order_type                         varchar(3),
    amount                                   numeric(18, 2),
    cnt                                      integer,
    status                                   varchar(128) not null
);

create table orders.business_response
(
    msg_id        VARCHAR(128) NOT NULL,
    sys_id        VARCHAR(128),
    tar_id        VARCHAR(128),
    main_id       VARCHAR(128),
    response_type int,
    result_code   int,
    PRIMARY KEY (msg_id)
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA orders TO sa;

--  storage
CREATE DATABASE storage;

-- Использование базы данных storage
\c storage;

-- create schema
CREATE SCHEMA storage AUTHORIZATION sa;

GRANT ALL PRIVILEGES ON DATABASE storage TO sa;

create table if not exists storage.all_orders
(
    id             bigint primary key generated by default as identity,
    acc         char(20)     not null,
    order_type_id  int          not null,
    date_order     timestamp    not null,
    id_order       varchar(128) not null,
    system_order   varchar(30)  not null,
    info           varchar(4000)
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA storage TO sa;