version: '3'
services:
  postgres:
    image: 'postgres:12.3'
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order_migration
